import { Link } from "react-router-dom";import { products } from "../data/products";import ProductCard from "../components/ProductCard";
const img=(id:string)=>products.find(p=>p.id===id)!.images[0];
export default function Home(){return <main><section className="hero"><div className="hero-image"/><div className="hero-copy"><p className="eyebrow">AVREN — MODERN ESSENTIALS</p><h1>MADE FOR<br/><em>THE EVERYDAY.</em></h1><p>Modern essentials, thoughtfully designed.</p><div><Link className="btn light" to="/shop/new-arrivals">Shop New Arrivals</Link><Link className="hero-link" to="/shop/essentials">Explore Essentials ↗</Link></div></div></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">01 — NEW IN</p><h2>New Arrivals</h2></div><Link to="/shop/new-arrivals">View all ↗</Link></div><div className="product-grid four">{products.filter(p=>p.badge==="NEW").slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="story"><div className="story-image"><img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1500&q=85"/></div><div className="story-copy"><p className="eyebrow">02 — THE AVREN STANDARD</p><h2>LESS,<br/><em>BUT BETTER.</em></h2><p>AVREN creates everyday clothing with a focus on thoughtful materials, comfortable silhouettes and timeless design. Pieces made to be worn often, lived in and kept around.</p><Link className="line-link" to="/about">Discover AVREN ↗</Link></div></section>
<section className="section categories"><div className="section-head"><div><p className="eyebrow">03 — EXPLORE</p><h2>Shop by Category</h2></div></div><div className="category-grid">{["ESSENTIALS","OUTERWEAR","SHIRTS","TROUSERS","ACCESSORIES"].map((x,i)=><Link key={x} to={`/shop/${x.toLowerCase()}`} className="category-tile"><img src={img(["tee-core","outer-structured","shirt-oxford","trouser-relaxed","cap"][i])}/><span>{x}</span><small>Explore ↗</small></Link>)}</div></section>
<section className="dark-editorial"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1800&q=85"/><div><p className="eyebrow">THE EVERYDAY EDIT</p><h2>BUILT FOR<br/><em>REAL LIFE.</em></h2><p>From slow mornings to late nights, AVREN is designed to move with you.</p><Link className="btn light" to="/shop">Explore the Collection</Link></div></section>
<section className="section"><div className="section-head"><div><p className="eyebrow">04 — MOST LOVED</p><h2>The AVREN Edit</h2><p>The pieces customers keep coming back to.</p></div><Link to="/shop">View all ↗</Link></div><div className="product-grid four">{products.filter(p=>p.badge==="BESTSELLER").map(p=><ProductCard key={p.id} product={p}/>)}</div></section>
<section className="trust"><div><b>Free Shipping</b><span>On orders over ₹2,999</span></div><div><b>Easy Returns</b><span>7-day returns</span></div><div><b>Secure Checkout</b><span>Your information is protected</span></div><div><b>Made to Last</b><span>Thoughtful materials</span></div></section>
<section className="newsletter"><p className="eyebrow">STAY IN THE LOOP</p><h2>Good things,<br/><em>occasionally.</em></h2><p>Get first access to new collections, limited releases and AVREN stories.</p><form onSubmit={e=>{e.preventDefault();(e.currentTarget.querySelector("button") as HTMLButtonElement).textContent="You're on the list."}}><input type="email" required placeholder="Enter your email"/><button>Subscribe</button></form></section></main>}